### ISSUE TITLE
Bibliography issues (Reviewer 1)

### ISSUE THREAD

**Issue by defeo** [erou/gf-h90-lattice#1]
- [x] [24] seem to be used on top of page 2 - but is never explained. I'd drop it - or explain the idea here.
- [x] [10] is cited with "to appear in 2011"? is this correct? If so, then they should include a link to some accessible document
- [x] [11] Fast arithmetics -> Fast arithmetic?
- [x] [14] lacks a year
- [x] [16] URL missing
- [x] [17] is this a paper? then the publication dates are missing, if this is a Web-page, the URL...
- [x] [21] needs a URL or copied into this paper
- [x] [23] publishing data
- [x] [24] remove - or explain
- [x] [25] trac ticket - on what server?
- [x] [29] URL missing. Furthermore, 8.0 is not the current version?

**Comment by erou** [comment]
Done in 8236cadf8cb1a1006703ddbf51f360cca062d6bb, dbd4be7f8242e5f7f5363059f6cead81937f46e7.
