### ISSUE TITLE
Minor remarks (rev 2+3)

### ISSUE THREAD

**Issue by defeo** [erou/gf-h90-lattice#3]
- [x] There are some “Overfull \hbox” to fix.
- [x] Page 1, line -2: “unique solutions”.
- [x] Page 3, “Conway polynomials and cyclotomic lattices” section: in line 4, I would insert a full stop after $pN$. In the line before the centered equation beginning with $C_l( ...$ the field is $F_{p^m}$.
- [x] Page 3, Section 3: in line 9 I would insert a full stop after “divisible by $p$”. The beginning of the statement of Proposition 1 could be replaced by “Any nonzero solution of (H90) for $\zeta_l$”.
- [x] Page 4, Corollary 7: in the statement, insert a semi-colon at the end of the first two items.
- [x] Page 5, Section 4: in the last line of the “Compatibility” paragraph the verb is “grow”. Five lines before Proposition 13, I would replace “ten first standard” with “first ten standard”. The same holds for the caption of Table 1.
- [x] Page 6, line before Definition 14: you use the field norm. Maybe you could define the symbol.
- [x] Page 7, statement of Proposition 21: in line 2 you should write “up to $d$”, while in line 4 you should remove the full stop before “operations”.
- [x] Page 7, proof of Proposition 21: in line 1, I would insert a full stop after $A_l$. In line -18 of the page, “Now, to compute”.
- [x] [8] Some details missing.
- [x] [10] `To appear...' is surely outdated.
- [x] [24] Personal communication in 1996 - to whom?

**Comment by erou** [comment]
- Overfull `\hbox`: d8aa2b493eaae4a0fe8eec53d19c2098053493c4
- some minor corrections: 0dcf81499c4a38004c6913f47176dcde228e69ce, e34807618f99957c0a3039b267bf2482d803b414
- bibliography: 8236cadf8cb1a1006703ddbf51f360cca062d6bb
